version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: eduflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: eduflow
      POSTGRES_PASSWORD: eduflow_password
      POSTGRES_DB: eduflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
